SERIAL_PORT = "/dev/ttyUSB0"
SERIAL_BAUDRATE = 115200

PIN_RED_LIGHT = 25
PIN_YELLOW_LIGHT = 26
PIN_GREEN_LIGHT = 27

RED_LIGHT_NORMAL = 30
RED_LIGHT_MEDIUM = 20
RED_LIGHT_BUSY = 10
GREEN_LIGHT_TIME = 27
YELLOW_LIGHT_TIME = 3

THRESHOLD_LOW = 5
THRESHOLD_MEDIUM = 15

WATCHDOG_TIMEOUT = 120
UPDATE_INTERVAL = 1.0
RECONNECT_DELAY = 5

DEBUG = True
LED_INDICATOR = True

ENABLE_MANUAL_MODE = True
MANUAL_BUTTON_PIN = 0