SERIAL_BAUDRATE = 115200
SERIAL_TIMEOUT = 1

PIN_RED_LIGHT = 25
PIN_YELLOW_LIGHT = 26
PIN_GREEN_LIGHT = 27

RED_LIGHT_MIN = 3
RED_LIGHT_MAX = 30
GREEN_LIGHT_MIN = 10
GREEN_LIGHT_MAX = 30
YELLOW_LIGHT_TIME = 3

THRESHOLD_CRITICAL = 20
THRESHOLD_HIGH = 14
THRESHOLD_LOW = 2

TIME_REDUCTION_PER_VEHICLE = 2

WATCHDOG_TIMEOUT = 2
UPDATE_INTERVAL = 1.0
BLINK_INTERVAL = 0.3

DEBUG = True